### ISSUE TITLE
Push latest image to dockerhub

### ISSUE THREAD

**Issue by samfranklin** [jncc/s2-ard-processor#44]
@CathyJinJNCC apologies for the indirect approach. Our email systems are down due to the global [crowdsrike issue](https://www.theregister.com/2024/07/19/crowdstrike_falcon_sensor_bsod_incident/), so I can't contact you any other way.

If you're able, can you please push an updated s2-ard-processor image to dockerhub and reply to this, so I can see it's done please. If you can't due to IT issues, also just let me know please. Thanks.

**Comment by CathyJinJNCC** [comment]
No worries I was just about to email you. The new image is up now: https://hub.docker.com/layers/jncc/s2-ard-processor/0.0.1.2/images/sha256-437776c1c2c489c03720371e0cf7b5f92393995857c1010ef3ad36547839b6bc?context=explore

Sorry took a bit longer than planned because there were also some shenanigans with the readme being missing (thanks for approving the PR).

**Comment by samfranklin** [comment]
Aha. Thanks for responding and pushing the image. That's all I need to crack on.
